data_config:
  dataset_dir: ../../Datasets/Aneurysm/S/one

train_config:
  epochs: 100
  batch_size: 6
  learning_rate: 0.0001
  output_dir: outputs
  log_step_freq: 1
  save_step_freq: 1
  seed: 1228
  num_workers: 8
  buffer_size: 12

